#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - master
  #     ↑↑↑ 改成你的分支名, 一般是master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
        #      ↑↑↑ 改成你的分支名, 一般是master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          echo "Deleting files, please wait ..."
          sudo rm -rf \
            /usr/share/dotnet \
            /etc/mysql \
            /etc/php
          sudo -E apt-get -y purge \
            azure-cli \
            ghc* \
            zulu* \
            hhvm \
            llvm* \
            firefox \
            google* \
            dotnet* \
            powershell \
            openjdk* \
            mysql* \
            php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Costom configure file
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # ========================固件定制部分========================
          # 

          # 
          # 如果不对本区块做出任何编辑, 则生成默认配置固件. 
          # 

          # 以下为定制化固件选项和说明:
          #

          #
          # 有些插件/选项是默认开启的, 如果想要关闭, 请参照以下示例进行编写:
          # 
          #          =========================================
          #         |  # 取消编译VMware镜像:                   |
          #         |  cat >> .config <<EOF                   |
          #         |  # CONFIG_VMDK_IMAGES is not set        |
          #         |  EOF                                    |
          #          =========================================
          #

          # 
          # 以下是一些提前准备好的一些插件选项.
          # 直接取消注释相应代码块即可应用. 不要取消注释代码块上的汉字说明.
          # 如果不需要代码块里的某一项配置, 只需要删除相应行.
          #
          # 如果需要其他插件, 请按照示例自行添加.
          # 注意, 只需添加依赖链顶端的包. 如果你需要插件 A, 同时 A 依赖 B, 即只需要添加 A.
          # 
          # 无论你想要对固件进行怎样的定制, 都需要且只需要修改 EOF 回环内的内容.
          # 

          # 编译4300/ar93xx/ar71xx固件:
          cat >> .config <<EOF
          CONFIG_TARGET_ath79=y
          CONFIG_TARGET_ath79_nand=y
          CONFIG_TARGET_ath79_nand_DEVICE_netgear_wndr4300=y
          EOF

          # 固件压缩:
          #cat >> .config <<EOF
          #CONFIG_TARGET_IMAGES_GZIP=y
          #EOF

          # 编译UEFI固件:
          #cat >> .config <<EOF
          #CONFIG_EFI_IMAGES=y
          #EOF

          # IPv6支持:
          #cat >> .config <<EOF
          #CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          #CONFIG_PACKAGE_ipv6helper=y
          #EOF

          # 多文件系统支持:
          #cat >> .config <<EOF
          #CONFIG_PACKAGE_kmod-fs-nfs=y
          #CONFIG_PACKAGE_kmod-fs-nfs-common=y
          #CONFIG_PACKAGE_kmod-fs-nfs-v3=y
          #CONFIG_PACKAGE_kmod-fs-nfs-v4=y
          #CONFIG_PACKAGE_kmod-fs-ntfs=y
          #CONFIG_PACKAGE_kmod-fs-squashfs=y
          #EOF

          # USB3.0支持:
          #cat >> .config <<EOF
          #CONFIG_PACKAGE_kmod-usb-ohci=y
          #CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          #CONFIG_PACKAGE_kmod-usb2=y
          #CONFIG_PACKAGE_kmod-usb2-pci=y
          #CONFIG_PACKAGE_kmod-usb3=y
          #EOF

          # 常用LuCI插件选择:
          #cat >> .config <<EOF
          #CONFIG_PACKAGE_luci-app-adbyby-plus=y
          #CONFIG_PACKAGE_luci-app-aria2=y
          #CONFIG_PACKAGE_luci-app-baidupcs-web=y
          #CONFIG_PACKAGE_luci-app-docker=y
          #CONFIG_PACKAGE_luci-app-frpc=y
          #CONFIG_PACKAGE_luci-app-hd-idle=y
          #CONFIG_PACKAGE_luci-app-kodexplorer=y
          #CONFIG_PACKAGE_luci-app-minidlna=y
          #CONFIG_PACKAGE_luci-app-openvpn=y
          #CONFIG_PACKAGE_luci-app-openvpn-server=y
          #CONFIG_PACKAGE_luci-app-qbittorrent=y
          #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          #CONFIG_PACKAGE_luci-app-ttyd=y
          #CONFIG_PACKAGE_luci-app-v2ray-server=y
          #CONFIG_PACKAGE_luci-app-verysync=y
          #CONFIG_PACKAGE_luci-app-webadmin=y
          #CONFIG_PACKAGE_luci-app-wireguard=y
          #CONFIG_PACKAGE_luci-app-wrtbwmon=y
          #EOF

          # LuCI主题:
          #cat >> .config <<EOF
          #CONFIG_PACKAGE_luci-theme-argon=y
          #CONFIG_PACKAGE_luci-theme-netgear=y
          #EOF

          # 常用软件包:
          #cat >> .config <<EOF
          #CONFIG_PACKAGE_curl=y
          #CONFIG_PACKAGE_htop=y
          #CONFIG_PACKAGE_nano=y
          #CONFIG_PACKAGE_screen=y
          #CONFIG_PACKAGE_tree=y
          #CONFIG_PACKAGE_vim-fuller=y
          #CONFIG_PACKAGE_wget=y
          #EOF

          # 取消编译VMware镜像以及镜像填充 (不要删除被缩进的注释符号):
          #cat >> .config <<EOF
          # CONFIG_TARGET_IMAGES_PAD is not set
          # CONFIG_VMDK_IMAGES is not set
          #EOF
          
          #从编译好的seed.config中复制
          cat >> .config <<EOF
          CONFIG_PACKAGE_6in4=y
          CONFIG_PACKAGE_boost=y
          CONFIG_PACKAGE_boost-date_time=y
          CONFIG_PACKAGE_boost-program_options=y
          CONFIG_PACKAGE_boost-system=y
          CONFIG_PACKAGE_frpc=y
          CONFIG_PACKAGE_ip6tables=y
          CONFIG_PACKAGE_ipt2socks=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          CONFIG_PACKAGE_iptables-mod-ipopt=y
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_kcptun-client=y
          CONFIG_PACKAGE_kmod-ifb=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          CONFIG_PACKAGE_kmod-ipt-ipopt=y
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-iptunnel=y
          CONFIG_PACKAGE_kmod-iptunnel4=y
          CONFIG_PACKAGE_kmod-nf-nat6=y
          CONFIG_PACKAGE_kmod-sched-cake=y
          CONFIG_PACKAGE_kmod-sched-core=y
          CONFIG_PACKAGE_kmod-sit=y
          CONFIG_PACKAGE_kmod-usb-printer=y
          CONFIG_PACKAGE_libevent2=y
          CONFIG_PACKAGE_libstdcpp=y
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-app-mwan3=y
          CONFIG_PACKAGE_luci-app-mwan3helper=y
          CONFIG_PACKAGE_luci-app-ntpc=y
          CONFIG_PACKAGE_luci-app-p910nd=y
          CONFIG_PACKAGE_luci-app-sqm=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Redsocks2=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin=y
          CONFIG_PACKAGE_luci-app-syncdial=y
          # CONFIG_PACKAGE_luci-app-unblockmusic is not set
          CONFIG_PACKAGE_luci-app-usb-printer=y
          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          CONFIG_PACKAGE_luci-i18n-mwan3-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-mwan3helper-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ntpc-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-p910nd-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-usb-printer-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wrtbwmon-zh-cn=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_luci-theme-netgear=y
          CONFIG_PACKAGE_mwan3=y
          CONFIG_PACKAGE_ntpclient=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
          CONFIG_PACKAGE_p910nd=y
          CONFIG_PACKAGE_redsocks2=y
          CONFIG_PACKAGE_shadowsocksr-libev-server=y
          CONFIG_PACKAGE_sqm-scripts=y
          CONFIG_PACKAGE_tc=y
          CONFIG_PACKAGE_trojan=y
          CONFIG_PACKAGE_v2ray=y
          CONFIG_PACKAGE_v2ray-plugin=y
          # CONFIG_PACKAGE_vsftpd-alt is not set
          CONFIG_TARGET_ROOTFS_TARGZ=y
          CONFIG_V2RAY_COMPRESS_UPX=y
          CONFIG_V2RAY_DISABLE_NONE=y
          CONFIG_V2RAY_EXCLUDE_ASSETS=y
          CONFIG_V2RAY_EXCLUDE_V2CTL=y
          CONFIG_V2RAY_JSON_INTERNAL=y
          CONFIG_boost-compile-visibility-hidden=y
          CONFIG_boost-runtime-shared=y
          CONFIG_boost-static-and-shared-libs=y
          CONFIG_boost-variant-release=y
          EOF
          
          # 
          # ========================固件定制部分结束========================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Download package source code
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s

      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: bin/targets
